### PR TITLE
Concurrency Exercise Equivalent Binary Trees solution modification

### PR DESCRIPTION
**Pull request by Ripounet**
The suggested solution, though clear and elegant, has the following flaws :
* it does not handle correctly trees of having different sizes.
* it does not distinguish a zero Value from a non-existant node value.

See my examples, before and after :
* http://play.golang.org/p/NrT6dfOJk8
* http://play.golang.org/p/fIJbWI0O4V

However I cannot guarantee right now that there are no goroutine leaks and channels leak (when Same has returned but values are still waiting in ch1 and ch2).

Thanks for this great book, we used it today for IRL bootcamp today in Paris, France!

### CODE REVIEW

**Comment by mattetti** [comment]
I'm sorry it took me so long to review, the PR doesn't apply anymore, would you mind rebasing so I can merge?

**Comment by mattetti** [comment]
@Ripounet je peux te rajouter en temps que collaborateur si tu veux.

**Comment by Ripounet** [comment]
Sure, I'd love to be a contributor.

**Comment by Ripounet** [comment]
I did what I could with the rebase command, and ended up with PR #38.
So I'm closing PR #32 now.

**Pull request closed without merging**
